language: android

android:
  components:
  - platform-tools
  - tools
  - android-23
  - build-tools-23.0.2
  - extra-google-m2repository
  - extra-android-m2repository

before_script:
  - GRADLE_OPTS="-Xms40m -Xmx3g -XX:MaxPermSize=3g"

script: "./gradlew check"

branches:
  except:
    - gh-pages

after_success:
  - ./gradlew jacocoTestReport coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a9870bec6049c7309e68
    on_success: change
    on_failure: always
